INSERT INTO driver (ID, DATE_CREATED, DELETED, ONLINE_STATUS, PASSWORD, USERNAME)
values (40, now(), false, 'ONLINE', 'password', 'driver-40');
INSERT INTO driver (ID, DATE_CREATED, DELETED, ONLINE_STATUS, PASSWORD, USERNAME)
values (41, now(), false, 'ONLINE', 'password', 'driver-41');
INSERT INTO driver (ID, DATE_CREATED, DELETED, ONLINE_STATUS, PASSWORD, USERNAME)
values (42, now(), false, 'OFFLINE', 'password', 'driver-42');

INSERT INTO car(ID, CONVERTIBLE, DATE_CREATED, ENGINE_TYPE, LICENSE_PLATE, MANUFACTURER, RATING, SEAT_COUNT, DRIVER_FK)
values (1, true, now(), 'GAS', 'EU-001', 'MANUFACTURER-X', 5.0, 4, 40);
INSERT INTO car(ID, CONVERTIBLE, DATE_CREATED, ENGINE_TYPE, LICENSE_PLATE, MANUFACTURER, RATING, SEAT_COUNT, DRIVER_FK)
values (2, true, now(), 'GAS', 'EU-002', 'MANUFACTURER-X', 2.0, 2, null);
INSERT INTO car(ID, CONVERTIBLE, DATE_CREATED, ENGINE_TYPE, LICENSE_PLATE, MANUFACTURER, RATING, SEAT_COUNT, DRIVER_FK)
values (3, true, now(), 'ELECTRIC', 'EU-03', 'MANUFACTURER-Y', 2.0, 3, null);
INSERT INTO car(ID, CONVERTIBLE, DATE_CREATED, ENGINE_TYPE, LICENSE_PLATE, MANUFACTURER, RATING, SEAT_COUNT, DRIVER_FK)
values (4, true, now(), 'ELECTRIC', 'EU-04', null, 2.0, 3, null);
INSERT INTO car(ID, CONVERTIBLE, DATE_CREATED, ENGINE_TYPE, LICENSE_PLATE, MANUFACTURER, RATING, SEAT_COUNT, DRIVER_FK)
values (5, false, now(), 'HYBRID', 'EU-05', 'MANUFACTURER-Z', 2.0, 3, 42);

